### ISSUE TITLE
/kitti/velo/pointcloud data seq =0

### ISSUE THREAD

**Issue by saintlrr** [tomas789/kitti2bag#31]
when I run `rostopic echo /kitti/velo/pointcloud/header`
the seq always equals to 0, do you now how to solve it to make the seq increase frame by frame.
```
---
seq: 0
stamp: 
  secs: 1317671741
  nsecs: 258542060
frame_id: "velo_link"
---
seq: 0
stamp: 
  secs: 1317671741
  nsecs: 362260103
frame_id: "velo_link"
---
seq: 0
stamp: 
  secs: 1317671741
  nsecs: 465951919
frame_id: "velo_link"

```
